document.addEventListener('DOMContentLoaded', () => {
  const quizData = [
    {
      question: "What is a key sign of fake news?",
      options: [
        "Verified author and publication date",
        "Sensational headline designed to trigger emotion",
        "Multiple corroborating sources",
        "Neutral, factual language"
      ],
      correctAnswer: 1,
      explanation: "Fake news often uses sensational, emotionally charged headlines (like ALL CAPS or extreme claims) to generate clicks and shares without providing factual substance."
    },
    {
      question: "What does a deepfake primarily use to create synthetic media?",
      options: [
        "Basic photo editing software like Photoshop",
        "Green screens and stunt doubles",
        "AI and machine learning (neural networks)",
        "Traditional 3D animation"
      ],
      correctAnswer: 2,
      explanation: "Deepfakes are generated by training Artificial Intelligence on thousands of images or audio clips to create highly realistic but entirely synthetic media."
    },
    {
      question: "Which URL is most suspicious and likely a phishing attempt?",
      options: [
        "https://google.com/search",
        "https://www.bbc.co.uk/news",
        "https://paypa1-secure-login.com/auth",
        "https://en.wikipedia.org/wiki/Phishing"
      ],
      correctAnswer: 2,
      explanation: "The 'paypa1' URL uses a lookalike character ('1' instead of 'l') and adds keywords like 'secure-login' to a non-standard domain, classic signs of phishing."
    },
    {
      question: "Why do social media algorithms often amplify misleading content?",
      options: [
        "Because algorithms can easily verify facts",
        "Because engineers specifically program them to lie",
        "Because sensational content generates more engagement (clicks, likes, comments)",
        "Because it costs less bandwidth to host fake news"
      ],
      correctAnswer: 2,
      explanation: "Algorithms are designed to maximize user engagement. Outrageous or sensational claims naturally draw more reactions, so the algorithm pushes them to more feeds regardless of accuracy."
    },
    {
      question: "When analyzing text, what does 'absolute language' (e.g., '100% proof', 'everyone knows') often indicate?",
      options: [
        "High credibility and rigorous fact-checking",
        "A neutral, journalistic tone",
        "Academic peer-review",
        "Potential bias or manipulation"
      ],
      correctAnswer: 3,
      explanation: "Legitimate reporting usually uses hedged language ('experts suggest', 'may indicate') because absolute certainty is rare. Absolute language is often a tactic to manipulate or persuade aggressively."
    },
    {
      question: "What is a 'Filter Bubble'?",
      options: [
        "A tool that blocks all internet advertisements",
        "A situation where an algorithm only shows you information that aligns with your past behavior and beliefs",
        "A secure way to browse the internet anonymously",
        "A type of physical screen protector for privacy"
      ],
      correctAnswer: 1,
      explanation: "Filter bubbles occur when algorithms learn your preferences and isolate you from opposing viewpoints, creating an 'echo chamber' that reinforces your existing beliefs."
    },
    {
      question: "Which of the following is a common visual flaw in a deepfake video?",
      options: [
        "Natural, rhythmic blinking",
        "Unnatural teeth rendering or blurring around the edges of the face",
        "Consistent lighting across the subject and background",
        "High resolution in the background"
      ],
      correctAnswer: 1,
      explanation: "AI often struggles to perfectly render fine details like individual teeth, hair strands, or the blending edge where a synthetic face meets the real head/background."
    },
    {
      question: "If an article claims a celebrity was caught doing something illegal, but you can't find the story on any major news network, it is likely:",
      options: [
        "A massive media cover-up",
        "Fake news lacking corroborating sources",
        "An exclusive scoop by an underground journalist",
        "Too new for major networks to notice"
      ],
      correctAnswer: 1,
      explanation: "Major news organizations aggressively compete for breaking news. If a massive story is entirely ignored by every legitimate outlet, it is almost certainly fake."
    },
    {
      question: "What is the difference between misinformation and disinformation?",
      options: [
        "They are exactly the same thing",
        "Misinformation is spread accidentally, disinformation is spread intentionally to deceive",
        "Disinformation is spread accidentally, misinformation is spread intentionally",
        "Misinformation only applies to social media"
      ],
      correctAnswer: 1,
      explanation: "Intent is the key difference. Disinformation is a malicious lie, while misinformation might just be someone sharing a rumor they genuinely believe is true."
    },
    {
      question: "What is the best immediate action to take if you receive an email from your 'bank' with an urgent link claiming your account will be suspended?",
      options: [
        "Click the link and quickly enter your password to secure the account",
        "Forward the email to all your contacts to warn them",
        "Do not click the link; instead, manually type your bank's website address into your browser and log in there",
        "Reply to the email asking if it's real"
      ],
      correctAnswer: 2,
      explanation: "Never click urgent links in unexpected emails. Manually navigating to the known, official website ensures you aren't being directed to a phishing page."
    }
  ];

  let currentQuestion = 0;
  let score = 0;
  let userAnswers = [];

  // DOM Elements
  const quizScreen = document.getElementById('quiz-screen');
  const resultsScreen = document.getElementById('results-screen');
  const currentQSpan = document.getElementById('current-q');
  const progressFill = document.getElementById('progress-fill');
  const questionText = document.getElementById('question-text');
  const optionsContainer = document.getElementById('options-container');
  const explanationBox = document.getElementById('explanation-box');
  const nextBtn = document.getElementById('next-btn');

  function loadQuestion() {
    const q = quizData[currentQuestion];
    
    // Update Progress
    currentQSpan.textContent = currentQuestion + 1;
    progressFill.style.width = `${((currentQuestion) / quizData.length) * 100}%`;
    
    // Reset UI
    questionText.textContent = q.question;
    optionsContainer.innerHTML = '';
    explanationBox.classList.remove('active');
    nextBtn.style.display = 'none';
    
    // Generate Options
    q.options.forEach((opt, index) => {
      const btn = document.createElement('button');
      btn.className = 'option-btn';
      btn.textContent = opt;
      btn.onclick = () => selectOption(index, btn);
      optionsContainer.appendChild(btn);
    });
  }

  function selectOption(selectedIndex, selectedBtn) {
    const q = quizData[currentQuestion];
    const isCorrect = selectedIndex === q.correctAnswer;
    
    // Save answer
    userAnswers.push({
      question: q.question,
      userAnswerStr: q.options[selectedIndex],
      correctAnswerStr: q.options[q.correctAnswer],
      isCorrect: isCorrect,
      explanation: q.explanation
    });

    if (isCorrect) score++;

    // Disable all options and highlight
    const allBtns = optionsContainer.querySelectorAll('.option-btn');
    allBtns.forEach((btn, index) => {
      btn.disabled = true;
      if (index === q.correctAnswer) {
        btn.classList.add('correct');
      } else if (index === selectedIndex && !isCorrect) {
        btn.classList.add('incorrect');
      }
    });

    // Show Explanation
    explanationBox.innerHTML = `<strong>${isCorrect ? 'Correct!' : 'Incorrect.'}</strong><br>${q.explanation}`;
    explanationBox.classList.add('active');
    
    nextBtn.style.display = 'inline-block';
  }

  nextBtn.addEventListener('click', () => {
    currentQuestion++;
    if (currentQuestion < quizData.length) {
      loadQuestion();
    } else {
      showResults();
    }
  });

  function showResults() {
    quizScreen.style.display = 'none';
    resultsScreen.style.display = 'block';
    
    // Final progress bar fill
    progressFill.style.width = '100%';

    document.getElementById('final-score').textContent = `${score}/${quizData.length}`;
    
    const gradeLabel = document.getElementById('grade-label');
    const feedbackText = document.getElementById('feedback-text');
    
    if (score >= 9) {
      gradeLabel.textContent = "Expert";
      gradeLabel.style.color = "#2ecc71";
      feedbackText.textContent = "Outstanding! You have a sharp eye for digital deception and are highly capable of navigating the web safely.";
    } else if (score >= 7) {
      gradeLabel.textContent = "Proficient";
      gradeLabel.style.color = "#f1c40f";
      feedbackText.textContent = "Great job! You know the basics well, though there are still a few advanced tactics to watch out for.";
    } else if (score >= 5) {
      gradeLabel.textContent = "Learning";
      gradeLabel.style.color = "var(--caput-mortuum)";
      feedbackText.textContent = "You're getting there! You spotted some obvious fakes, but deceptive content can still trick you. Review the modules for more practice.";
    } else {
      gradeLabel.textContent = "Needs Review";
      gradeLabel.style.color = "#e74c3c";
      feedbackText.textContent = "It looks like digital deception is still tricky for you. We strongly recommend going back through the TrustNet modules to build your defenses.";
    }

    // Build Review Section
    const reviewContainer = document.getElementById('review-container');
    reviewContainer.innerHTML = '';
    
    userAnswers.forEach((ans, i) => {
      const item = document.createElement('div');
      item.className = `review-item ${ans.isCorrect ? 'review-correct' : 'review-incorrect'}`;
      
      item.innerHTML = `
        <h4 style="margin-bottom: 10px; color: var(--space-cadet);">Q${i+1}: ${ans.question}</h4>
        <p style="font-size: 14px; margin-bottom: 5px;"><strong>Your Answer:</strong> ${ans.userAnswerStr}</p>
        ${!ans.isCorrect ? `<p style="font-size: 14px; margin-bottom: 5px; color: #27ae60;"><strong>Correct Answer:</strong> ${ans.correctAnswerStr}</p>` : ''}
        <p style="font-size: 14px; color: var(--slate-gray); margin-top: 10px;"><em>${ans.explanation}</em></p>
      `;
      reviewContainer.appendChild(item);
    });
  }

  document.getElementById('retake-btn').addEventListener('click', () => {
    currentQuestion = 0;
    score = 0;
    userAnswers = [];
    resultsScreen.style.display = 'none';
    quizScreen.style.display = 'block';
    loadQuestion();
  });

  // Start Quiz
  loadQuestion();
});
